name: 'Setup Node Environment'
description: 'Sets up Bun, installs dependencies, and configures caching'

inputs:
  bun-version:
    description: 'Bun version to install'
    required: false
    default: 'latest'
  cache-key-suffix:
    description: 'Additional suffix for cache key'
    required: false
    default: ''
  frozen-lockfile:
    description: 'Use frozen lockfile for reproducible installs'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Setup Bun Runtime
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ inputs.bun-version }}
        
    - name: Cache Dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.bun/install/cache
          node_modules
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}${{ inputs.cache-key-suffix }}
        restore-keys: |
          ${{ runner.os }}-bun-
          
    - name: Install Dependencies
      shell: bash
      run: |
        if [ "${{ inputs.frozen-lockfile }}" = "true" ]; then
          bun install --frozen-lockfile
        else
          bun install
        fi