# Example: Branch to Environment Mapping Configuration
# Demonstrates how to configure branch-to-environment mappings for different operations

name: SST Deployment with Branch Mappings

on:
  push:
    branches: [main, develop, 'feature/*', 'hotfix/*']
  pull_request:
    branches: [main, develop]

jobs:
  # Deploy to production when pushing to main
  deploy-production:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy to Production
        uses: kodehort/sst-ops-action@v0.5.0
        with:
          operation: deploy
          token: ${{ secrets.GITHUB_TOKEN }}
          branch-mappings: |
            {
              "deploy": {
                "main": "production",
                "develop": "staging"
              }
            }

  # Deploy to staging when pushing to develop
  deploy-staging:
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy to Staging
        uses: kodehort/sst-ops-action@v0.5.0
        with:
          operation: deploy
          token: ${{ secrets.GITHUB_TOKEN }}
          branch-mappings: |
            {
              "deploy": {
                "main": "production",
                "develop": "staging"
              }
            }

  # Run diff against development environment for all PRs
  preview-changes:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Preview Infrastructure Changes
        uses: kodehort/sst-ops-action@v0.5.0
        with:
          operation: diff
          token: ${{ secrets.GITHUB_TOKEN }}
          branch-mappings: |
            {
              "diff": {
                "*": "development"
              }
            }

  # Complex mapping example with multiple patterns
  advanced-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy with Advanced Branch Mapping
        uses: kodehort/sst-ops-action@v0.5.0
        with:
          operation: deploy
          token: ${{ secrets.GITHUB_TOKEN }}
          branch-mappings: |
            {
              "deploy": {
                "main": "production",
                "develop": "staging",
                "feature/user-auth": "auth-testing",
                "hotfix/*": "hotfix-env",
                "*": "pr-preview"
              },
              "diff": {
                "main": "staging",
                "develop": "development",
                "*": "development"
              },
              "remove": {
                "main": "production"
              }
            }

  # Trunk-based development example
  trunk-based-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Trunk-based Deployment
        uses: kodehort/sst-ops-action@v0.5.0
        with:
          operation: deploy
          token: ${{ secrets.GITHUB_TOKEN }}
          # All feature branches deploy to preview environments
          # Main branch deploys to production
          branch-mappings: |
            {
              "deploy": {
                "main": "production",
                "*": "preview"
              },
              "diff": {
                "main": "production",
                "*": "staging"
              }
            }

  # Environment-specific remove operations
  cleanup-environments:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/cleanup/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Remove Preview Environment
        uses: kodehort/sst-ops-action@v0.5.0
        with:
          operation: remove
          token: ${{ secrets.GITHUB_TOKEN }}
          branch-mappings: |
            {
              "remove": {
                "cleanup/preview": "preview",
                "cleanup/feature": "feature-env",
                "*": "development"
              }
            }