name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build Distribution
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install
        
      - name: Type check
        run: bun run typecheck
        
      - name: Lint
        run: bun run lint
        
      - name: Test
        run: bun test
        
      - name: Build action
        run: bun run build
        
      - name: Verify bundle exists
        run: |
          if [ ! -f "dist/index.js" ]; then
            echo "Build failed: dist/index.js not found"
            exit 1
          fi
          
      - name: Check bundle size
        run: |
          BUNDLE_SIZE=$(stat -f%z dist/index.js 2>/dev/null || stat -c%s dist/index.js)
          BUNDLE_SIZE_MB=$((BUNDLE_SIZE / 1024 / 1024))
          echo "Bundle size: ${BUNDLE_SIZE_MB}MB"
          
          if [ $BUNDLE_SIZE_MB -gt 10 ]; then
            echo "❌ Bundle size exceeds 10MB limit! Current: ${BUNDLE_SIZE_MB}MB"
            exit 1
          else
            echo "✅ Bundle size is within 10MB limit: ${BUNDLE_SIZE_MB}MB"
          fi
          
      - name: Test bundle execution
        run: |
          echo "Testing bundle execution..."
          timeout 10s node dist/index.js || true
          echo "✅ Bundle is executable"
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ github.sha }}
          path: dist/
          retention-days: 30