name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  NODE_VERSION: '20'
  BUN_VERSION: 'latest'

jobs:
  quality-gates:
    name: Quality Gates
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Environment
        uses: ./.github/actions/setup-node-env
        with:
          bun-version: ${{ env.BUN_VERSION }}
          cache-key-suffix: -quality
        
      - name: Type Check
        run: bun run typecheck
        
      - name: Lint
        run: bun run lint
        
      - name: Test with Coverage
        run: bun run test:coverage
        
      - name: Upload Coverage Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-${{ github.sha }}
          path: coverage/
          retention-days: 30

  build-and-verify:
    name: Build & Verify
    runs-on: ubuntu-latest
    needs: quality-gates
    outputs:
      bundle-size: ${{ steps.bundle-info.outputs.size }}
      bundle-hash: ${{ steps.bundle-info.outputs.hash }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Environment
        uses: ./.github/actions/setup-node-env
        with:
          bun-version: ${{ env.BUN_VERSION }}
          cache-key-suffix: -build
          
      - name: Build Distribution
        run: bun run build
        
      - name: Extract Bundle Information
        id: bundle-info
        run: |
          # Check bundle exists
          if [ ! -f "dist/index.js" ]; then
            echo "❌ Bundle file dist/index.js not found"
            exit 1
          fi
          
          # Get bundle size and hash
          BUNDLE_SIZE=$(stat -f%z dist/index.js 2>/dev/null || stat -c%s dist/index.js)
          BUNDLE_SIZE_MB=$((BUNDLE_SIZE / 1024 / 1024))
          BUNDLE_HASH=$(sha256sum dist/index.js | cut -d' ' -f1)
          
          echo "size=${BUNDLE_SIZE_MB}MB" >> $GITHUB_OUTPUT
          echo "hash=${BUNDLE_HASH}" >> $GITHUB_OUTPUT
          
          echo "📦 Bundle size: ${BUNDLE_SIZE_MB}MB"
          echo "🔒 Bundle hash: ${BUNDLE_HASH:0:16}..."
          
          # Verify bundle size limit
          if [ $BUNDLE_SIZE_MB -gt 10 ]; then
            echo "❌ Bundle size exceeds 10MB limit!"
            exit 1
          fi
          
      - name: Test Bundle Execution
        run: |
          echo "🧪 Testing bundle execution..."
          timeout 30s node -c dist/index.js
          echo "✅ Bundle syntax validation passed"
          
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ github.sha }}
          path: dist/
          retention-days: 30

  check-dist:
    name: Check Distribution
    runs-on: ubuntu-latest
    needs: build-and-verify
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Environment
        uses: ./.github/actions/setup-node-env
        with:
          bun-version: ${{ env.BUN_VERSION }}
          
      - name: Build Distribution
        run: bun run build
        
      - name: Compare Distribution
        id: diff
        run: |
          if [ ! -d dist/ ]; then
            echo "❌ Expected dist/ directory does not exist"
            ls -la ./
            exit 1
          fi
          
          if [ "$(git diff --ignore-space-at-eol --text dist/ | wc -l)" -gt "0" ]; then
            echo "❌ Detected uncommitted changes after build"
            git diff --ignore-space-at-eol --text dist/
            echo "::warning::Distribution files are not up to date. Run 'bun run build' and commit changes."
            exit 1
          fi
          
          echo "✅ Distribution is up to date"
          
      - name: Upload Expected Distribution
        if: failure() && steps.diff.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: expected-dist-${{ github.sha }}
          path: dist/
          retention-days: 7

  summary:
    name: CI Summary
    runs-on: ubuntu-latest
    needs: [quality-gates, build-and-verify, check-dist]
    if: always()
    
    steps:
      - name: Generate Summary
        run: |
          echo "## 🚀 CI Pipeline Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          # Quality Gates Status
          if [ "${{ needs.quality-gates.result }}" = "success" ]; then
            echo "✅ **Quality Gates**: All checks passed" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ **Quality Gates**: Failed" >> $GITHUB_STEP_SUMMARY
          fi
          
          # Build Status
          if [ "${{ needs.build-and-verify.result }}" = "success" ]; then
            echo "✅ **Build & Verify**: Bundle created successfully" >> $GITHUB_STEP_SUMMARY
            echo "   - Size: ${{ needs.build-and-verify.outputs.bundle-size }}" >> $GITHUB_STEP_SUMMARY
            echo "   - Hash: \`${{ needs.build-and-verify.outputs.bundle-hash }}\`" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ **Build & Verify**: Failed" >> $GITHUB_STEP_SUMMARY
          fi
          
          # Distribution Check Status
          if [ "${{ needs.check-dist.result }}" = "success" ]; then
            echo "✅ **Distribution Check**: Up to date" >> $GITHUB_STEP_SUMMARY
          elif [ "${{ needs.check-dist.result }}" = "failure" ]; then
            echo "❌ **Distribution Check**: Out of sync" >> $GITHUB_STEP_SUMMARY
          else
            echo "⏭️ **Distribution Check**: Skipped" >> $GITHUB_STEP_SUMMARY
          fi
          
      - name: Set Status
        run: |
          if [ "${{ needs.quality-gates.result }}" != "success" ] || [ "${{ needs.build-and-verify.result }}" != "success" ]; then
            echo "❌ CI pipeline failed"
            exit 1
          elif [ "${{ needs.check-dist.result }}" = "failure" ]; then
            echo "⚠️ CI pipeline completed with warnings (distribution out of sync)"
            exit 1
          else
            echo "✅ CI pipeline completed successfully"
          fi